name: smile_care
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use for State Management with GetX
  get: ^4.6.6

  # Use for responsive UI
  flutter_screenutil: ^5.9.0

  device_preview: ^1.1.0

  image_picker: ^1.1.1

  cupertino_icons: ^1.0.6

  intl: any
  
  shared_preferences: ^2.2.3
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.1
  async: ^2.11.0


  flutter_localizations:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/